In [5]:
obs_dim = 8
act_dim = 4
hidden_sizes = [64]*5

sizes = [obs_dim] + list(hidden_sizes) + [act_dim]

print(sizes)

[8, 64, 64, 64, 64, 64, 4]


In [10]:
import torch
from torch.optim import Adam
import torch.nn as nn
from solution import Agent 

In [11]:
from lunar_lander import LunarLander
# from gym.wrappers.monitoring.video_recorder import VideoRecorder

env = LunarLander()
env.seed(0)

obs_dim = [8]
act_dim = []

# initialize agent
agent = Agent(env)

In [12]:
agent.actor

Actor(
  (logits_net): Sequential(
    (layer0): Linear(in_features=8, out_features=64, bias=True)
    (activation0): Tanh()
    (layer1): Linear(in_features=64, out_features=64, bias=True)
    (activation1): Tanh()
    (layer2): Linear(in_features=64, out_features=4, bias=True)
    (activation2): Identity()
  )
)

In [14]:
from collections import OrderedDict

model = nn.Sequential(OrderedDict([
          ('conv1', nn.Conv2d(1,20,5)),
          ('relu1', nn.ReLU()),
          ('conv2', nn.Conv2d(20,64,5)),
          ('relu2', nn.ReLU())
        ]))

model

Sequential(
  (conv1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
  (relu1): ReLU()
  (conv2): Conv2d(20, 64, kernel_size=(5, 5), stride=(1, 1))
  (relu2): ReLU()
)

In [30]:
import numpy as np

_ = np.arange(20)
ptr = 20
path_start_idx = 3
path_slice = slice(path_start_idx, ptr)

print(_[path_slice])

print(_[path_start_idx:ptr])

print(np.cumsum(_[path_start_idx:ptr]))

x = _[0:10]
gamma = 1
discount_cumsum = np.zeros_like(x)
discount_cumsum[-1] = x[-1]
for t in reversed(range(x.shape[0] - 1)):
    discount_cumsum[t] = x[t] + gamma * discount_cumsum[t + 1]

print(discount_cumsum)

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  3   7  12  18  25  33  42  52  63  75  88 102 117 133 150 168 187]
[45 45 44 42 39 35 30 24 17  9]


In [33]:
from scipy import signal

x = [1,2,3,4,5]
coef = 1

signal.lfilter([1], [1, float(-coef)], x[::-1], axis=0)[::-1]

array([15., 14., 12.,  9.,  5.])

In [8]:

import random

import numpy as np
import matplotlib.pyplot as plt

import time

import scipy.signal
from gym.spaces import Box, Discrete

import torch
from torch.optim import Adam
import torch.nn as nn

## Newly added
from torch.distributions import Categorical
import torch.nn.functional as F

def mlp(sizes, activation, output_activation=nn.Identity):
    """
    The basic multilayer perceptron architecture used.

    Parameters
    ----------
    sizes: List
        List of feature sizes, i.e., 
            [indput_dim, hidden_layer_1, ..., hidden_layer_n_dim, output_dim] 

    activation: nn.Module
        Activation function for the hidden layers.

    output_activation: nn.Module
        Activation function for the output layer


    Returns
    -------
    mlp: nn.Module

    """

    # TODO: Implement this function.
    # Hint: Use nn.Sequential to stack multiple layers of the network.
    print(sizes, len(sizes))
    print(activation)
    print(output_activation)
    mlp = nn.Sequential()
    for i in range(len(sizes)-1):
        print(i)
        mlp.add_module('layer' + str(i), nn.Linear(sizes[i],sizes[i+1]))
        if i != len(sizes)-2:
            mlp.add_module('activation' + str(i), activation())
        else:
            mlp.add_module('activation' + str(i), output_activation())

    return mlp

class Actor(nn.Module):
    """A class for the policy network."""

    def __init__(self, obs_dim, act_dim, hidden_sizes, activation):
        super().__init__()
        self.logits_net = mlp([obs_dim] + list(hidden_sizes) + [act_dim], activation)

hid = 64  # layer width of networks
l = 2  # layer number of networks
hidden_sizes = [hid]*l
obs_dim = 8
activation=nn.Tanh

actor =  Actor(obs_dim, 4, hidden_sizes, activation)


[8, 64, 64, 4] 4
<class 'torch.nn.modules.activation.Tanh'>
<class 'torch.nn.modules.linear.Identity'>
0
1
2


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [15]:
rews = np.append([1,2], 1)
print(rews)

[1 2 1]


In [1]:
from gym.envs.classic_control import rendering
from gym.wrappers.monitoring.video_recorder import VideoRecorder
from lunar_lander import LunarLander

env = LunarLander()
env.seed(0)
rec = VideoRecorder(env, "policy.mp4")
rec.capture_frame()
rec.close()



AttributeError: 'ImageData' object has no attribute 'data'

: 

In [1]:
import gym
env = gym.make("LunarLander-v2", render_mode="human")
env.action_space.seed(42)

observation, info = env.reset(seed=42)

for _ in range(1000):
    observation, reward, terminated, truncated, info = env.step(env.action_space.sample())

    if terminated or truncated:
        observation, info = env.reset()

env.close()

TypeError: __init__() got an unexpected keyword argument 'render_mode'